services:
  assignment-3-postgres-container:
    image: postgres:14.19
    volumes:
      - type: bind
        source: ./setup.sql
        target: /docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: assignment-password
